import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import RootProvider from "../provider/RootProvider";
import { Footer } from "./components/Footer";
import { Header } from "./components/Header";
import "./globals.css";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bliq Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </RootProvider>
      </body>
    </html>
  );
}
